print(f"Welcome to the Band Name Generator")
print(f"What's is the name of the city you grew up in?")
city = input()
print("What's your pet's name?")
pet_name = input()
print(f"Your band name could be {city} {pet_name}")
